baseurl = "https://hoptoplounge.com/"
languageCode = "en-us"
title = "HopTopLounge"
theme = "creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "HopTop Lounge"
	description = "Best Sports Bar in Gainesville"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "HopTop Lounge"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Best Sports Bar in Gainesville"
		subtitle   = "Come for the drinks, stay for the drinks, they really are the best."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-beer"
            title = "Best Beers"
            description = "Our templates are updated regularly so they don't break."

        [[params.services.list]]
			icon = "fa-bolt"
			title = "Quick Service"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-gamepad"
            title = "Fun and Games"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "You have to make your websites with love these days!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Click below to find us!"

		[params.aside.button]
			text = "Directions"
			link = "//www.google.com/maps/place/Hop+top+Lounge/@29.636049,-82.3381921,15z/data=!4m5!3m4!1s0x0:0x294b549347384661!8m2!3d29.636049!4d-82.3381921"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your weekend early? Have any accomodations? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "(352) 224-5575"
		email = "feedback@hoptoplounge.com"
        facebook = "https://www.facebook.com/hoptoplounge/"
        twitter = "https://www.facebook.com/hoptoplounge/"
        instagram = "https://www.facebook.com/hoptoplounge/"


     #Google Maps section
     #[params.location]
         #latitude  = "34.007850"
         #longitude = "-118.499305"
         #maps_api_key = ""
